name: Build and Deploy Azure function

on:
  push:
    branches: 
        main

#Configuration
env:
  AZURE_FUNCTIONAPP_NAME: your-app-name    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'


jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run test --if-present
        npm test
        
    - name: Publish Azure Functions
      uses: Azure/functions-action@v1.3.2
      with:
        # Name of the Azure Function App
        app-name: Resume Page Counter
        # Path to package or folder. *.zip or a folder to deploy
        package: backend
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        
