name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v2.0.0
        with:
          source_dir: 'front'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          sync: true
